[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]
aptPkgs = ["chromium", "fonts-liberation", "libasound2", "libatk-bridge2.0-0", "libatk1.0-0", "libatspi2.0-0", "libdrm2", "libgtk-3-0", "libnspr4", "libnss3", "libwayland-client0", "libxcomposite1", "libxdamage1", "libxrandr2", "xvfb"]

[phases.install]
cmds = ["npm ci"]

[phases.start]
cmds = ["npm run start"]